### ISSUE TITLE
Basic Project Info

### ISSUE THREAD

**Issue by leahbannon** [18F/dashboard#1]
Basic info to display about each project:
- Name
- Short description
- Date of last public demo/upcoming demo
- Contact info
- Rough start date
- Client
- License(s)
- Blog posts about the project
- API 1st project? (yes/no) (link to API docs)
- IAs/MOUs

**Comment by gbinal** [comment]
Some loose ideas on how to manage the text - https://github.com/18F/18f.gsa.gov/issues/113
