### ISSUE TITLE
github stats not coming through

### ISSUE THREAD

**Issue by gbinal** [18F/dashboard#120]
But just for one project: [api.data.gov](http://18f.github.io/dashboard/project/api-data-gov/).  I can't figure out what's up.  

![screen shot 2014-10-23 at 11 09 45 am](https://cloud.githubusercontent.com/assets/633088/4755570/b7aac382-5ac6-11e4-817e-234d9d291f0e.png)

**Comment by gboone** [comment]
I don't think it's just api.data.gov, it's any project not on GovCode. Ah, nm this is a different issue than the govcode one. Thanks for pointing it out, @gbinal

**Comment by gbinal** [comment]
It appears that every other project on the dashboard has stats coming through.

**Comment by leahbannon** [comment]
Looks like it's just Mirage and api.data.gov that aren't getting data, right?

**Comment by gboone** [comment]
Dashboard only supports 18F repos at the moment, so that's why we're not seeing anything for the NREL repo. (The latter must have been added recently?) But I have a fix for the api.data.gov coming up shortly (jQuery selector problem). 

Mirage doesn't appear to be on GovCode, so that's why we are missing data for that one.

**Comment by gbinal** [comment]
Mirage is working for me.  

![screen shot 2014-10-23 at 11 31 32 am](https://cloud.githubusercontent.com/assets/633088/4755961/b4c41008-5ac9-11e4-9da3-709c4d2c916c.png)

**Comment by leahbannon** [comment]
Ah, well that would explain Mirage. It's working, just not accurate.

**Comment by gboone** [comment]
@gbinal grabbing data for the NREL will have to wait. I just don't have time to spend on that right now. Sorry, but api.data.gov should start to show again after #121.
