### ISSUE TITLE
Use project description for open graph tags

### ISSUE THREAD

**Issue by konklone** [18F/dashboard#124]
Here's me linking to a project page in Slack:

![og tags](https://cloud.githubusercontent.com/assets/4592/4758572/837b9036-5ae0-11e4-9001-51aeb9b6f742.png)

It's got the project title in there, but not the project description. (Which right now sort of implies that myRA _is_ 18F. :smile_cat:)

**Comment by gboone** [comment]
This should be closed as of #192
