### ISSUE TITLE
Link to partner agency?

### ISSUE THREAD

**Issue by konklone** [18F/dashboard#125]
This seems begging for a link to Treasury's website:

![og tags](https://cloud.githubusercontent.com/assets/4592/4758628/d94450ac-5ae0-11e4-99c5-9a0d25599d8e.png)

It might be less necessary for Treasury, but for lesser-known partners it could be a help.

**Comment by phildini** [comment]
Looking at this ticket and trying to understand the ask, here.

On the dashboard home:
![dash-home-suggestion](https://cloud.githubusercontent.com/assets/710999/6851295/6ff6100c-d39b-11e4-9892-6076dfdd4841.png)

On a project detail:
![dash-detail-suggestion](https://cloud.githubusercontent.com/assets/710999/6851304/82ac51de-d39b-11e4-816d-1c9a1201ec30.png)

Is this what people had in mind?

**Comment by phildini** [comment]
I dug into this more. In order to do this correctly, the data should come from the 18f/hub api. I have code ready for both 18f/hub and this repo that will solve this issue, but the data for hub comes from a private repo that I don't have access to, so I'm fairly stuck.
