### ISSUE TITLE
Add footer about contact us about dashboard

### ISSUE THREAD

**Issue by leahbannon** [18F/dashboard#129]

**Comment by leahbannon** [comment]
Possible text...

Questions? Feedback? Curious about getting dashboard for your agency? [Email us] or [open an issue] on GitHub.

1: 18f@gsa.gov
2: https://github.com/18F/dashboard/issues/new

**Comment by meiqimichelle** [comment]
@leahbannon do you want this before go-live?

**Comment by meiqimichelle** [comment]
See #133 for initial commit.

**Comment by meiqimichelle** [comment]
Closed with #133
