### ISSUE TITLE
add 'alpha' tag to dashboard

### ISSUE THREAD

**Issue by leahbannon** [18F/dashboard#132]
How can we do this without totally confusing everyone? Should dashboard be a project in the project list? Maybe include with solicitation for feedback/contact us?

**Comment by meiqimichelle** [comment]
If we're going to add an alpha tag on the site, then I think it should be on the project list, too.

As for a tag on the site in general, Noah M. has a pretty non-intrusive version of the alpha tag we could use -- looks like a little gray alert at the top of the page.

**Comment by meiqimichelle** [comment]
I added Noah's version of 'hey this site is in alpha' to the top of the page with the latest push to #133 . Picture is in that comment chain. What do you think @leahbannon ?

**Comment by meiqimichelle** [comment]
Closed with #133
