### ISSUE TITLE
myRA Impact Description

### ISSUE THREAD

**Issue by cscairns** [18F/dashboard#140]
Change to:

For the millions of Americans who don't have access to employer-sponsored retirement plans. This includes roughly half of all workers and 75% of part-time workers.

**Comment by leahbannon** [comment]
As far as I can tell, this is the same, except for some grammar fixes. Sorry - what am I missing?

**Comment by cscairns** [comment]
currently it says "employee-sponsored"...it's employer

**Comment by leahbannon** [comment]
Will be fixed here #141
