### ISSUE TITLE
links to blog posts about the project

### ISSUE THREAD

**Issue by leahbannon** [18F/dashboard#15]
breaking out #1

**Comment by leahbannon** [comment]
link to tags on tumblr?

**Comment by leahbannon** [comment]
@gboone Hey where are we on getting tagging working? You said that's almost done, right?

**Comment by gboone** [comment]
Yeah, I have it working locally. It doesn't seem to be working on the staging server yet but I'm looking into that now.

**Comment by gboone** [comment]
Actually, it is working on staging, but the page layout looks a little wonky.

**Comment by leahbannon** [comment]
This is implemented. Now working on remaining issue with this: #66
