### ISSUE TITLE
more descriptive link text

### ISSUE THREAD

**Issue by jpyuda** [18F/dashboard#154]
The project stages page has four "learn more" links -- this can make for a sub-par experience for screen reader users, as many such users will have their screen reader read them all of the links on the page -- in a context like that, it's nearly impossible to know where the links go.

I suggest something more descriptive like "Learn more about the alpha stage.", etc.

**Comment by gboone** [comment]
Huge thanks, @jpyuda, definitely a huge accessibility miss for us here.
