### ISSUE TITLE
Add FBOpen mobile app to impact for FBOpen

### ISSUE THREAD

**Issue by adelevie** [18F/dashboard#156]
Any thoughts on this?

**Comment by leahbannon** [comment]
This is an interesting idea. I don't think it belongs in impact, but I was thinking it would be good to advertise our API first strategy in a few different ways, and this could be a great component of that. Legal might give us a hard time about advertising private companies on a gov site, though. @aaronsnow what do you think?

**Comment by aaronsnow** [comment]
I think it'd be awesome to have a roll/list somewhere of all the apps --
for-profit, not-for-profit, or gov -- that use the FBOpen API and/or
@amoose's widget. If we couch it that way, and encourage people to submit
pull requests to add their apps, I can't imagine anyone would object.

On Fri, Nov 14, 2014 at 3:05 PM, Leah Bannon notifications@github.com
wrote:

> This is an interesting idea. I don't think it belongs in impact, but I was
> thinking it would be good to advertise our API first strategy in a few
> different ways, and this could be a great component of that. Legal might
> give us a hard time about advertising private companies on a gov site,
> though. @aaronsnow https://github.com/aaronsnow what do you think?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/18F/dashboard/issues/156#issuecomment-63121524.

## 

Aaron Snow
18F https://18f.gsa.gov/ Deputy Executive Director, Delivery
aaron.snow@gsa.gov

**Comment by NoahKunin** [comment]
Can't do, too much bureaucracy overhead, would _actually_ be an endorsement. This needs to be on a self-service / wiki platform instead (push to us instead of pull). Will contemplate when staff become available to extend the Dashboard.
