### ISSUE TITLE
Link from 18f.gsa.gov?

### ISSUE THREAD

**Issue by konklone** [18F/dashboard#160]
Does the dashboard project want to be linked to from the main `18f.gsa.gov` page?

**Comment by leahbannon** [comment]
We'd like to iterate on some user feedback first. Everyone scattered to new projects once we launched alpha. Hopefully we'll get something out in the next couple weeks.

**Comment by NoahKunin** [comment]
It appears the Dashboard was left in `alpha` without a Product Owner. I'm going to submit myself tomorrow in Project Intake as the responsible executive for the 18F System Inventory.
