### ISSUE TITLE
meta description tag should be based on page content

### ISSUE THREAD

**Issue by ultrasaurus** [18F/dashboard#178]
https://18f.gsa.gov/dashboard/project/midas/

looks like this when posted on Slack:
![image](https://cloud.githubusercontent.com/assets/41906/5723084/235fdbb6-9af6-11e4-95dc-47e8741fc603.png)

assume it would be similar for Facebook / Twitter

We could update:

```
  <meta name="description" content="18F builds effective, user-centric digital services focused on the interaction between government and the people and businesses it serves.">
  <meta property="og:description" content="18F builds effective, user-centric digital services focused on the interaction between government and the people and businesses it serves.">
```

to include text from project description, instead of the generic 18F description.

**Comment by gboone** [comment]
This should be closed as of #192
