### ISSUE TITLE
When I click on a stage...

### ISSUE THREAD

**Issue by rjmajma** [18F/dashboard#189]
Quick suggestion! One of the things I want to do when I check out the dashboard is see which products are in which stage. Normally, I click on a stage and expect to see each of the products in that stage. Right now, it takes you to an explanation of each of those stages. 

Not sure if you've heard this from others, but knowing what projects are in each stage by organizing them via those stages is something I've wanted in the site.

**Comment by esgoodman** [comment]
+1 to this suggestion.
