### ISSUE TITLE
add save ferris 

### ISSUE THREAD

**Issue by gbinal** [18F/dashboard#203]

**Comment by gboone** [comment]
paging @jpyuda is it work splitting this out of the "MyUSCIS Projects" collection?

**Comment by jpyuda** [comment]
Save Ferris is not an independent project, but is in fact part of the broader work we're doing with USCIS on bringing all of their customer-facing experiences together. Given, especially, that a large part of this effort is based around the premise of _not_ treating different apps as different silos, but presenting them to customers as a unified front, it would be counterproductive to present them as separate projects here.

I'd still like to figure out how we can communicate on the dashboard that parts of the USCIS work are quite far along while other parts are notional, with everything in between. But listing them as separate projects isn't the way to do that.

**Comment by gbinal** [comment]
Reopening this issue with an idea for how to do represent all this well:  Add the new save ferris implementation as a project link on https://18f.gsa.gov/dashboard/project/uscis/.  

It's standard on a lot of of the dashboard projects to include a links section and adding it would seem to make sense in that vein.  

@gboone - I can't recall if there are instructions on how to file pull requests to the dashboard, but if you can point me to that or let me know which branch is right, I'm happy to offer this as a pull request.

**Comment by gboone** [comment]
I'm fine with that tack but to be clear, whether and how Save Ferris is represented on the Dashboard is @jpyuda's decision. John, if you're down to include it I'm happy to. 

To answer your question, @gbinal modifying projects for Dashboard involves sending pull requests to [18F/data-private](https://github.com/18F/data-private/) and changing the project's respective file in the projects repo there. That will update it on the Hub and Dashboard.

**Comment by gbinal** [comment]
Sounds great - thanks.

**Comment by jpyuda** [comment]
@gboone let's spend some time next week to figure out how to holistically talk about the work we're doing.

**Comment by NoahKunin** [comment]
Save Ferris is an internal codename. The Dashboard will update with the links that have become public, but that will be addressed not in this issue.
