### ISSUE TITLE
staff on the project

### ISSUE THREAD

**Issue by leahbannon** [18F/dashboard#24]
Who is working on this project? Little profile images?

**Comment by leahbannon** [comment]
Contractor support?

**Comment by leahbannon** [comment]
I finished gathering the data on this (although some folks are missing because they're not on the site at all. Working on that...) Reassigning to implement on project pages... possibly as little b&w icons?

**Comment by meiqimichelle** [comment]
Got it. Will check with @gboone on whether we worked out a way to pull from the 18F site team yml.

**Comment by gboone** [comment]
In theory there's a way to do it. All depends on whether the JSON file generated with 18F/18f.gsa.gov#296 is served correctly. Another thing I hope to troubleshoot with nginx configs.

**Comment by gboone** [comment]
Okay, 18F/18f.gsa.gov#296 was merged and we should be able to pull team data out of 18f.gsa.gov soon. I'm going to get something going on this that pulls out of staging just to get something in front of @meiqimichelle
