### ISSUE TITLE
Provide anchor links for project stages

### ISSUE THREAD

**Issue by vdavez** [18F/dashboard#243]
This comes up from time to time where I want a link to the particular stage in a project. Would be nice to do https://18f.gsa.gov/dashboard/stages#beta or https://18f.gsa.gov/dashboard/stages#alpha. Not urgent, but...

**Comment by afeld** [comment]
You already can! Click the stage names from the top of https://18f.gsa.gov/dashboard/.

**Comment by vdavez** [comment]
Oh. Right. :grimacing: Thanks @afeld!
