### ISSUE TITLE
projects missing from stages page

### ISSUE THREAD

**Issue by afeld** [18F/dashboard#252]
Just got pointed out to me in an interview:

![18f_ _project_stage_definitions](https://cloud.githubusercontent.com/assets/86842/9766794/d52ba5ba-56e8-11e5-9cba-625e7b289963.png)

**Comment by DavidEBest** [comment]
This should be fixed with #255, which has been merged into staging. What is necessary to get it into production?

**Comment by DavidEBest** [comment]
@gboone What is the process to move the fix for this from staging into production?

**Comment by gboone** [comment]
Pull request from the `staging` branch to the `production` branch. I'll get one going and tag you on it.

**Comment by DavidEBest** [comment]
Fixed with #262.
