### ISSUE TITLE
EKIP API not appearing in production

### ISSUE THREAD

**Issue by gboone** [18F/dashboard#263]
The EKIP team [added an .about.yml file about a week ago](https://github.com/18F/ekip-api/blob/master/.about.yml) but the project has not yet appeared on the Dashboard. Perhaps it's due to a validation error. cc: @OpenGlobe @mbland

**Comment by mbland** [comment]
```
Parse error in the file: could not find expected ':' while scanning a simple key at line 79 column 1
```

The `impact:` field has a line break, and doesn’t use YAML multiline syntax.

**Comment by DavidEBest** [comment]
Submitted PR to ekip to correct the error. https://github.com/18F/ekip-api/pull/222
