### ISSUE TITLE
about.yml parse errors should cause an annotation on project page...

### ISSUE THREAD

**Issue by ultrasaurus** [18F/dashboard#264]
about.yml parse errors should cause an annotation on project page, ideally with a link to the specific error and a link to the failing about.yml file

depends on https://github.com/18F/team-api.18f.gov/issues/122

**Comment by DavidEBest** [comment]
@ultrasaurus @gboone @mbland Just to be clear - the dashboard is a public-facing resource. Are we all okay with putting the errors there? Or should they be exposed to the team via another mechanism?

**Comment by mbland** [comment]
As a potential alternative, we could parse the "contact" field and either send an email or post an issue. That'd be a little more work, but it'd probably be a more reliable mechanism.

**Comment by gbinal** [comment]
FWIW - I'm okay with errors being publicly visible on the dashboard.

**Comment by ultrasaurus** [comment]
I'm ok with it too -- it's real!  Also if we point to the about.yaml, then people can find the actual information.  The yaml might be intimiditating for some folks, but if anyone really needs the info, that will be able to read it.

**Comment by ultrasaurus** [comment]
love that idea @mbland -- wrote it up as a separate issue: https://github.com/18F/dashboard/issues/269.  Let's do this first, then add the notification!

**Comment by DavidEBest** [comment]
In progress here: https://github.com/18F/team-api.18f.gov/issues/122

**Comment by ultrasaurus** [comment]
from sprint planning @gboone thinks this is good for now.  Improvements may be opened in the future as seprate stories.
