### ISSUE TITLE
add api link (if present)

### ISSUE THREAD

**Issue by ultrasaurus** [18F/dashboard#266]
optional - 
- link to API
- notes field: just be text for now, ideally markdown so it could include links, like ("experimental" or "beta" or "sign up at api.data.gov for an API key"

**Comment by DavidEBest** [comment]
Do we want to hold off on this (and the process links) until we figure out the standardization & release mechanism for the schema? Or try to get them implemented before the next 'release'?

**Comment by DavidEBest** [comment]
I think we should be able to close this. That okay with everyone?
