### ISSUE TITLE
C2 Related link text is broken

### ISSUE THREAD

**Issue by noahmanger** [18F/dashboard#273]
![image](https://cloud.githubusercontent.com/assets/1696495/10674463/cb6187c8-78af-11e5-99b8-5204aa2eade5.png)

**Comment by pkarman** [comment]
thanks, I think this is already fixed in master but we just haven't deployed it yet. See https://github.com/18F/C2/pull/727 -- is that the same issue?

**Comment by noahmanger** [comment]
Oh probably.

On Thu, Oct 22, 2015 at 11:30 AM, Peter Karman notifications@github.com
wrote:

> thanks, I think this is already fixed in master but we just haven't
> deployed it yet. See 18F/C2#727 https://github.com/18F/C2/pull/727 --
> is that the same issue?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/18F/dashboard/issues/273#issuecomment-150314921.

## 

Noah Manger
18F http://18f.gsa.gov | Work: 415-696-6146

**Comment by mbland** [comment]
Nope, that file is fixed. There were other errors preventing the Team API from rebuilding, addressed by 18F/18f.gsa.gov#1268 and 18F/openFEC#1291.

We'll get this brittleness fixed soon.

**Comment by mbland** [comment]
OK, this is all good now:

![dashboard-c2-fixed](https://cloud.githubusercontent.com/assets/301547/10677945/4c76f622-78dd-11e5-8c56-84386ab83071.png)
