### ISSUE TITLE
Project stage filters are not working

### ISSUE THREAD

**Issue by mtorres253** [18F/dashboard#292]
To duplicate
go to https://18f.gsa.gov/dashboard/
click on any one of the project stages (discovery, alpha, beta, live)

Expected behavior: you go to a page showing all projects in that stage

Actual behavior: you see an error (webpage not available)

**Comment by DavidEBest** [comment]
@mtorres253 This appears to be resolved. Safe to close?

**Comment by ultrasaurus** [comment]
yep, I believe this is fixed!
