### ISSUE TITLE
as a product manger, I would like to preview my dashboard page before merging to master branch of my repo

### ISSUE THREAD

**Issue by ultrasaurus** [18F/dashboard#302]
goal is to be able to see what the dashboard page will look like, making sure we stay in sync with dashboard and team API code

**Comment by ultrasaurus** [comment]
@jeremiak and I will pair this week, with advice from @DavidEBest

**Comment by jeremiak** [comment]
Now live: https://18f.gsa.gov/dashboard/project/preview/?url=https://github.com/18F/dashboard/blob/staging/.about.yml
