### ISSUE TITLE
display projects with sub-projects

### ISSUE THREAD

**Issue by ultrasaurus** [18F/dashboard#305]
based on [Open Opps mockup](https://docs.google.com/a/gsa.gov/document/d/13JsT_0iecI_bKufI6R8fc0TM5GOXzHGE2AgRHkep9Q0/pub) and TBD USCIS mockup, display projects that have related projects/repos, via child-about.yml's

**Comment by DavidEBest** [comment]
Does the Open Opps mockup really reflect the intention of this? That example includes two different concepts of parent-child relationships.

There are two code repos represented in the Open Opps project (each conceivably with their own .about.yml file) and two projects (Open Opps & Gov Connect). Which parent-child relationship should I be modeling with this issue? @ultrasaurus @gboone 

Either one could be modeled with the parent attribute, I'd need to add something to about_yml to handle both (on second thought, I _think_ we could do it with the fields we have, but it might be a little unintuitive).

**Comment by DavidEBest** [comment]
This is related to issue #267.

**Comment by ultrasaurus** [comment]
the following proposal was agreed upon in Sprint Demo:
- repo link type
- if it is in a related links list, we don't promote as full-fledged project 

Would be nice for all 18F repos to have an about.yml
