### ISSUE TITLE
Team API now returns 'blogTag' instead of 'blog'

### ISSUE THREAD

**Issue by mtorres253** [18F/dashboard#310]
@gboone Same data, different label. So, this issue is for dashboard to consume this change.

**Comment by mtorres253** [comment]
https://github.com/18F/about_yml/issues/46

**Comment by ultrasaurus** [comment]
would be good to look for both 'blog' and 'blogTag' for now (preference on blogTag though we never expect both) -- this will make migration to new schema easier
