### ISSUE TITLE
Incorrect link for betaFEC

### ISSUE THREAD

**Issue by melodykramer** [18F/dashboard#334]
Clicking on betaFEC takes you to a 404: https://18f.gsa.gov/dashboard/project/betafec

**Comment by DavidEBest** [comment]
@gboone This works locally for me, but both staging and production are broken.

**Comment by gboone** [comment]
Guessing this is a capitalization thing. Stupid HFS+, https://18f.gsa.gov/dashboard/project/betaFEC/ is the URL it should point at, there _should_ be a redirect to make the URL respond to both `betafec` and `betaFEC` See #330

**Comment by quepol** [comment]
Confirming the CAPS thing. If you click the `Metrics` link it is being generated correctly: https://18f.gsa.gov/dashboard/project/betaFEC
