### ISSUE TITLE
legend for project status

### ISSUE THREAD

**Issue by quepol** [18F/dashboard#34]
- create a legend for project status (discovery, alpha, beta, etc.)
- color code each status type

**Comment by meiqimichelle** [comment]
I started a branch for this called project-description-page, but @gboone I couldn't figure out how to get it to display. I'm not sure how you did the sub-page folder business. Right now the page is called status.html and is just in root (...which I also can't display from for unknown reasons).

**Comment by gboone** [comment]
Do you have it as a fully separate page or a template in the `_includes/` directory that we just drop in to the project.html layout? (Also, have you pushed branch up for this yet?)

**Comment by meiqimichelle** [comment]
I just made it a fully separate page (based on the `index.html` page, which is based on `bare` template). The branch should be there: https://github.com/18F/dashboard/tree/project-description-page

**Comment by gboone** [comment]
Closed by #93. http://18f.github.io/dashboard/stages/
