### ISSUE TITLE
Site not ready to be run under HTTPS

### ISSUE THREAD

**Issue by konklone** [18F/dashboard#50]
If you visit https://18f.github.io/dashboard/, you'll see a ton of warnings in the console - fonts won't load, and the GovCode API can't be hit.

The GovCode API thing is a blocker, unless you proxy it somehow - its URL is `http://api.govcode.org` and it doesn't respond to `https://`, so it can't be fetched from an `https://` page until it does. You could proxy all requests through nginx or something (like we did for `https://18f.gsa.gov/listserv` for GSA's Hydra service) but it'd be much better if GovCode added `https://` support. 

The font links have two problems - they are hardcoded to `http://18f.github.io` URLs, but even when updated to `https://`, they will only work for that website exactly. It'd be better to make those URLs relative (starting with a `/`) if possible.

cc @dlapiduz

**Comment by meiqimichelle** [comment]
@konklone the font thing is a known issue. See #42. However, thinking about it now with a fresh brain, even if #42 is not fully addressed, I should be able to change those paths to relative to gh-pages (I hope). So, add `baseurl` path but not `http://18f.github.io`. I will look into that. Thx!

**Comment by meiqimichelle** [comment]
Okay, changed the font.css to relative in #53 and it doesn't seem to have broken anything. Good. This does not resolve #42, but at least helps on this issue!

**Comment by dlapiduz** [comment]
@konklone thanks for the ping. The govcode api now supports https (you need to change the url since http is also available).

**Comment by gboone** [comment]
I'll work on changing around the govcode api URLs today. Thanks @dlapiduz!

**Comment by konklone** [comment]
Looks good to me -- I see 0 console warnings when I visit https://18f.github.io/dashboard/ and open the developer console.

**Comment by leahbannon** [comment]
@konklone are we good on this? can I close this issue?

**Comment by gboone** [comment]
@leahbannon merge #122 and we're good. This should close itself.
