### ISSUE TITLE
hide news link for projects w/o blog posts

### ISSUE THREAD

**Issue by leahbannon** [18F/dashboard#66]

**Comment by gboone** [comment]
I'll do a hackey JavaScript version of this for now and then work on a better solution further down the road.

**Comment by leahbannon** [comment]
New plan, as discussed: Create data type in yaml file in which we can list the blog tags manually. If no tags are listed, hide the text/link to blog posts.

**Comment by gboone** [comment]
Okay, I'm going to build this in so it works once we have #88.

My plan is to expect the tags to come in as a comma separated list on a field called `tags` like:

```
tags: open government, transparency, how we work
```
