### ISSUE TITLE
mobile issues

### ISSUE THREAD

**Issue by leahbannon** [18F/dashboard#75]
- [ ] chevrons aren't working on iPhone/iPad Safari
- [ ] text overlapping

**Comment by leahbannon** [comment]
![img_1966](https://cloud.githubusercontent.com/assets/4323988/4583070/4e88add4-4fee-11e4-9d78-16b578dcf27a.jpg)
![img_1967](https://cloud.githubusercontent.com/assets/4323988/4583072/4e91559c-4fee-11e4-9056-01fbac27e1cf.jpg)
![img_1968](https://cloud.githubusercontent.com/assets/4323988/4583071/4e8d08d4-4fee-11e4-95b1-fe267f5d58a6.jpg)

**Comment by meiqimichelle** [comment]
Addressed with #90.
