### ISSUE TITLE
contact emails are currently going to github.com/[email address]

### ISSUE THREAD

**Issue by leahbannon** [18F/dashboard#80]
Is this an issue with how I entered the data?

**Comment by meiqimichelle** [comment]
I'll take a look. I had it set to detect if there was an '@' in the contact field and then make the link an email address instead of a normal link, but maybe other updates changed the way that path works, and made my solution not work. Will investigate :)

**Comment by gboone** [comment]
Ah, no, I'll take a look at it.

**Comment by gboone** [comment]
@meiqimichelle you beat me to it.

**Comment by meiqimichelle** [comment]
My filter isn't working, that is the problem. I'm apparently having trouble with filters in general -- getting strange behavior, I must be doing something wrong. @gboone feel free to you, might be obvious where the issue is.
