### ISSUE TITLE
license link doesn't work if LICENSE is not on master branch

### ISSUE THREAD

**Issue by leahbannon** [18F/dashboard#82]
Ex: 18F/doi-extractives-data uses gh-pages branch

**Comment by leahbannon** [comment]
also issue with /Developer Program: https://github.com/18F/API-All-the-X/blob/gh-pages/LICENSE.md

**Comment by gboone** [comment]
Plan: create an optional licenseBranch field in the YAML. 
Looks like this:

```
licenseBranch:
  repo: branch
```

If you put a branch name in there it will override the default `master` branch.

**Comment by gboone** [comment]
Better(?) idea:

```
licenses:
  repo_name:
  - license
  - branch
```

Example

```
licenses:
  doi-extractives-data:
    - cc0
    - gh-pages
```

I think that will give us `license => {doi-extractives-data => {cc0, gh-pages}}`

**Comment by gboone** [comment]
Even though it adds more fields to the yml file, I think the first plan will be easier template side.
