### ISSUE TITLE
C2 project page isn't generating?

### ISSUE THREAD

**Issue by leahbannon** [18F/dashboard#84]

**Comment by meiqimichelle** [comment]
Probably that the slug in the yml file and the name of the html page don't match -- did we change any of those slugs in the recent updates to the data?

**Comment by meiqimichelle** [comment]
@leahbannon this page is generating for my locally now, not sure why it was gone or why it re-appeared :-/ Hopefully this will carry through when #89 is merged.

**Comment by gboone** [comment]
This is staggeringly strange. It's generating locally but not [on GH pages](http://18f.github.io/dashboard/project/C2/)

**Comment by meiqimichelle** [comment]
So strange! Maybe conflicting...something?? myRA is also still behaving strangely -- it loads, but loads empty.

**Comment by meiqimichelle** [comment]
Ok, fixed the myRA problem -- capitalizations didn't match between yml title and html project page name.

**Comment by gboone** [comment]
Closed via #99
