### ISSUE TITLE
Design primary/secondary partner view

### ISSUE THREAD

**Issue by meiqimichelle** [18F/dashboard#86]
- Take out (s) and make it magic (detect number of partners and add)
- Create slot for secondary folks in design.

**Comment by meiqimichelle** [comment]
#89 creates the slot and removes the 's' on the project pages (well, dynamically adds/removes). I could not recreate this dynamic effect on the dashboard home, not sure why. @gboone can you take a look?

**Comment by gboone** [comment]
The dynamic 's' thing should be good to go in #89 now.

**Comment by meiqimichelle** [comment]
Awesome! That covers both the points in this issue so closing.
